require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")

-- spec("user.lspsaga")
-- spec("user.trouble")

spec("user.alpha")
spec("user.astral")
spec("user.cmp")
spec("user.colorschemes.catppuccin")
spec("user.colorschemes.eldritch")
spec("user.colorschemes.gruvbox")
spec("user.comment")
spec("user.devicons")
spec("user.gitsigns")
spec("user.indentline")
spec("user.lspconfig")
spec("user.lualine")
spec("user.mason")
spec("user.mason-null-ls")
spec("user.neogit")
spec("user.none-ls")
spec("user.nvimtree")
spec("user.projects")
spec("user.schemastore")
spec("user.telescope")
spec("user.todo")
spec("user.toggleterm")
spec("user.treesitter")
spec("user.whichkey")

require("user.lazy")
