require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")

spec("user.alpha")
spec("user.cmp")
spec("user.colorscheme")
spec("user.comment")
spec("user.devicons")
spec("user.gitsigns")
spec("user.lspconfig")
spec("user.lualine")
spec("user.mason")
spec("user.neogit")
spec("user.none-ls")
spec("user.nvimtree")
spec("user.projects")
spec("user.schemastore")
spec("user.telescope")
spec("user.toggleterm")
spec("user.treesitter")
spec("user.whichkey")
spec("user.indentline")

require("user.lazy")
