return {
  "nvim-treesitter/nvim-treesitter",
  branch = "master",
  lazy = false,
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "asm",
        "bash",
        "c",
        "cmake",
        "comment",
        "cpp",
        "dockerfile",
        "editorconfig",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "linkerscript",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "ninja",
        "printf",
        "regex",
        "ssh_config",
        "tmux",
        "todotxt",
        "toml",
        "yaml",
      },
    })
  end,
  build = ":TSUpdate",
}
